import Vue from 'vue'

import 'babel-polyfill'

import Mint from 'mint-ui'

import App from './App.vue' // app 容器
import router from './router/index'
import store from './store/index'
import utils from './util/util'
import validator from './util/validator'
import wxApi from './util/wxapi'
import Accounting from 'accounting' // 金钱相关
import baiduTongji from 'baidu-tongji' // 百度统计
import growingio from 'vue-growingio' // gio埋点
import $cookie from 'js-cookie'

import 'mint-ui/lib/style.css'
import './assets/style/reset.scss'
import './assets/style/common.scss'
import './assets/style/my-mint.scss'
import './assets/style/font.scss'

import './util/mixin_handleGoBack'
import './util/mixin_handleScrollTopForKeepAlive'

import VueAwesomeSwiper from 'vue-awesome-swiper'
import 'swiper/dist/css/swiper.css'
Vue.use(VueAwesomeSwiper)

// 将时间戳转成日期
Vue.filter('convertTime', function(timeStamp) {
  return utils.formatDate('YYYY-MM-DD HH:mm:ss', timeStamp)
})
// 将时间戳转成人性化日期（当前 显示 时分，当年显示月日+时分 else 年 + 月日 + 时分）
Vue.filter('formatDateLocal', function(timeStamp) {
  return utils.formatDateLocal(timeStamp)
})
// 金额格式化
Vue.filter('formatMoney', function(value) {
  return utils.formatMoney(value, false)
})

// 百度统计
window._hmt = []
if (process.env.NODE_ENV === 'production') {
  baiduTongji('10a7b4ab2cfd45aabaaf2d1ae68be42e')
}

// 测试
if (process.env.NODE_ENV === 'test') {
  require('./util/vconsole.js')
}

// 注册全局公用组件
import './components/common'

Vue.use(Mint)

if (process.env.NODE_ENV === 'production') {
  Vue.use(growingio, {
    siteId: '9aaee6bb838ff65f',
    config: {
      hashtag: true
    }
  })
}
Vue.prototype.utils = utils
Vue.prototype.validator = validator
Vue.prototype.wxApi = wxApi
Vue.prototype.$accounting = Accounting
Vue.prototype.$cookie = $cookie

// 系统时间
import { getSysTime } from './util/getSysTime'
Vue.prototype.getSysTime = getSysTime
// 自动修正系统 时钟偏移
import './util/autoFixSysTime'

// 页面跳转至外链时 定义的公用方法
import { pageJump } from './util/pageJump'
Vue.prototype.Jump = pageJump

import api from './api/WorkorderMessage.js'

// 将API方法绑定到全局
Vue.prototype.$api = api
Vue.config.productionTip = false

//埋点
import './util/directive_buryPoint'

// hhApp bridge相关处理
import './util/appBridgeReady'
// 提供给app调用的 定义在window上面的方法
import './assets/js/for-HHApp'

// sentry
// 文档: https://github.com/791045873/notes/issues/15
// todo: sourcemap => https://juejin.im/post/5cc2b8b9e51d456e40377319
//       sentry-cli releases -o report -p hhyw-h5fe new pro@1.0.5
//       sentry-cli releases -o report -p hhyw-h5fe files pro@1.0.5 upload-sourcemaps ../ecshop/h5/static/js --url-prefix ~/h5/static/js
//       rm ../ecshop/h5/static/js/*.js.map
//
//       把 sourcemap 上传后删除 map: https://github.com/40thieves/webpack-sentry-plugin
import * as Sentry from '@sentry/browser'
import * as Integrations from '@sentry/integrations'
if (process.env.VUE_APP_SENTRY_DSN) {
  Sentry.init({
    environment: process.env.NODE_ENV,
    dsn: process.env.VUE_APP_SENTRY_DSN,
    release: 'pro@1.0.5',
    integrations: [new Integrations.Vue({ Vue, attachProps: true })]
  })
  Vue.prototype.$sentry = Sentry
}

// matomo
// 文档: https://www.npmjs.com/package/vue-matomo
// http://www.matomo.net.cn/category/tutorial/page/2/
// https://developer.matomo.org/api-reference/tracking-javascript
import VueMatomo from 'vue-matomo'
Vue.use(VueMatomo, {
  // Configure your matomo server and site by providing
  host: process.env.VUE_APP_SENTRY_URL,
  siteId: process.env.VUE_APP_SENTRY_ID,

  // Changes the default .js and .php endpoint's filename
  // Default: 'piwik'
  trackerFileName: 'matomo',

  // Overrides the autogenerated tracker endpoint entirely
  // Default: undefined
  // trackerUrl: 'https://example.com/whatever/endpoint/you/have',

  // Enables automatically registering pageviews on the router
  // router: router,

  // Enables link tracking on regular links. Note that this won't
  // work for routing links (ie. internal Vue router links)
  // Default: true
  enableLinkTracking: false,

  // Require consent before sending tracking information to matomo
  // Default: false
  requireConsent: false,

  // Whether to track the initial page view
  // Default: true
  trackInitialView: false,

  // Whether or not to log debug information
  // Default: false
  debug: false,

  // UserID passed to Matomo (see https://developer.matomo.org/guides/tracking-javascript-guide#user-id)
  // Default: undefined
  userId: undefined
})

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#appMall')
